# Generated by Django 4.2.28 on 2026-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerbalance',
            name='provider',
            field=models.CharField(choices=[('mtn', 'MTN'), ('vodafone', 'Vodafone'), ('airtel', 'Airtel'), ('tigo', 'Tigo'), ('ecobank', 'Ecobank'), ('fidelity', 'Fidelity'), ('cal_bank', 'Cal Bank'), ('cash', 'Cash')], max_length=20),
        ),
    ]
