# Generated by Django 4.2.28 on 2026-02-28 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_pending_verification_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_remove_company_branch_notes_add_unique_constraints'),
        ('transactions', '0003_rename_transaction_to_agentrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentrequest',
            new_name='transaction_company_7cb7b7_idx',
            old_name='agentreq_company_reqat_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrequest',
            new_name='transaction_company_c52f6a_idx',
            old_name='agentreq_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrequest',
            new_name='transaction_company_c6f313_idx',
            old_name='agentreq_company_type_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrequest',
            new_name='transaction_referen_c695df_idx',
            old_name='agentreq_reference_idx',
        ),
        migrations.AddField(
            model_name='agentrequest',
            name='bank',
            field=models.CharField(blank=True, choices=[('ecobank', 'Ecobank'), ('gcb', 'GCB Bank'), ('fidelity', 'Fidelity Bank'), ('cal_bank', 'Cal Bank'), ('stanbic', 'Stanbic Bank'), ('absa', 'Absa Bank'), ('uba', 'UBA'), ('access', 'Access Bank'), ('zenith', 'Zenith Bank'), ('republic', 'Republic Bank'), ('prudential', 'Prudential Bank'), ('fnb', 'First National Bank'), ('standard_chartered', 'Standard Chartered'), ('societe_generale', 'Societe Generale'), ('boa', 'Bank of Africa'), ('adb', 'Agricultural Dev Bank'), ('fab', 'First Atlantic Bank'), ('omnibsic', 'OmniBSIC Bank'), ('nib', 'National Investment Bank'), ('arb_apex', 'ARB Apex Bank')], default='', help_text='Select the bank (only when channel is Bank).', max_length=30),
        ),
        migrations.AddField(
            model_name='agentrequest',
            name='mobile_network',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN'), ('vodafone', 'Vodafone'), ('airteltigo', 'AirtelTigo')], default='', help_text='Select the network (only when channel is Mobile Money).', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentrequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_requests', to='core.company'),
        ),
        migrations.AlterField(
            model_name='agentrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_requests', to='customers.customer'),
        ),
    ]
