# Generated by Django 4.2.28 on 2026-03-01 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0004_add_bank_and_mobile_network_to_agent_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='The agent who submitted this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
