# Generated by Django 4.2.28 on 2026-03-01 12:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def merge_airtel_tigo_to_airteltigo(apps, schema_editor):
    """Merge separate 'airtel' and 'tigo' provider balances into 'airteltigo'."""
    ProviderBalance = apps.get_model("transactions", "ProviderBalance")

    for old_provider in ("airtel", "tigo"):
        for row in ProviderBalance.objects.filter(provider=old_provider):
            # Check if an 'airteltigo' record already exists for this user+company
            existing = ProviderBalance.objects.filter(
                company=row.company, user=row.user, provider="airteltigo"
            ).first()
            if existing:
                # Merge: sum both balances
                existing.starting_balance += row.starting_balance
                existing.balance += row.balance
                existing.save()
                row.delete()
            else:
                # Rename in place
                row.provider = "airteltigo"
                row.save()


def mark_existing_approved_as_completed(apps, schema_editor):
    """Mark all previously approved requests as completed since they were
    historically treated as final upon approval (before settlement existed)."""
    AgentRequest = apps.get_model("transactions", "AgentRequest")
    AgentRequest.objects.filter(status="approved").update(status="completed")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0005_add_requested_by_to_agent_request'),
    ]

    operations = [
        # 1. Schema: add settlement fields to AgentRequest
        migrations.AddField(
            model_name='agentrequest',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrequest',
            name='settled_by',
            field=models.ForeignKey(blank=True, help_text='The agent who settled (executed) this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_requests', to=settings.AUTH_USER_MODEL),
        ),
        # 2. Schema: remove cash channel from AgentRequest
        migrations.AlterField(
            model_name='agentrequest',
            name='channel',
            field=models.CharField(choices=[('bank', 'Bank'), ('mobile_money', 'Mobile Money')], max_length=20),
        ),
        # 3. Data: merge airtel/tigo → airteltigo BEFORE changing choices
        migrations.RunPython(
            merge_airtel_tigo_to_airteltigo,
            migrations.RunPython.noop,
        ),
        # 4. Schema: update provider choices (removes airtel, tigo; adds airteltigo)
        migrations.AlterField(
            model_name='providerbalance',
            name='provider',
            field=models.CharField(choices=[('mtn', 'MTN'), ('vodafone', 'Vodafone'), ('airteltigo', 'AirtelTigo'), ('ecobank', 'Ecobank'), ('fidelity', 'Fidelity'), ('cal_bank', 'Cal Bank'), ('cash', 'Cash')], max_length=20),
        ),
        # 5. Data: mark existing approved requests as completed
        migrations.RunPython(
            mark_existing_approved_as_completed,
            migrations.RunPython.noop,
        ),
    ]
