# Generated by Django 4.2.28 on 2026-03-09 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_add_pending_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('velocity', 'Velocity Check'), ('amount_spike', 'Amount Spike'), ('odd_hours', 'Odd Hours Activity'), ('cross_bank', 'Cross-Bank Anomaly'), ('dormant_account', 'Dormant Account Activity')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('bank', models.CharField(blank=True, default='', help_text='Leave blank to apply globally across all banks.', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('threshold_amount', models.DecimalField(blank=True, decimal_places=2, help_text='For amount_spike: multiplier above average to flag.', max_digits=12, null=True)),
                ('threshold_count', models.IntegerField(blank=True, help_text='For velocity/cross_bank: max count before flagging.', null=True)),
                ('threshold_window_minutes', models.IntegerField(default=60, help_text='Time window in minutes.')),
                ('odd_hour_start', models.IntegerField(default=22, help_text='Hour (0-23) fraud window starts.')),
                ('odd_hour_end', models.IntegerField(default=5, help_text='Hour (0-23) fraud window ends.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_rules', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('bank', models.CharField(blank=True, default='', max_length=100)),
                ('signal_type', models.CharField(max_length=30)),
                ('severity', models.CharField(default='medium', max_length=10)),
                ('description', models.TextField()),
                ('risk_score', models.FloatField(default=0.0, help_text='0.0 to 1.0')),
                ('related_transaction_id', models.UUIDField(blank=True, null=True)),
                ('related_transaction_type', models.CharField(blank=True, default='', max_length=30)),
                ('evidence', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Under Review'), ('confirmed', 'Confirmed Fraud'), ('dismissed', 'Dismissed'), ('auto_cleared', 'Auto-Cleared')], default='open', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=100)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_signals', to='core.company')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='fraud.fraudrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('performed_by', models.CharField(default='system', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='fraud.fraudsignal')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='fraudsignal',
            index=models.Index(fields=['company', 'status'], name='fraud_fraud_company_ed8d00_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudsignal',
            index=models.Index(fields=['company', 'severity'], name='fraud_fraud_company_b0afcc_idx'),
        ),
    ]
