# Generated by Django 4.2.28 on 2026-03-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_company_branch_notes_add_unique_constraints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='bank_or_network',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='bank',
            field=models.CharField(blank=True, choices=[('ecobank', 'Ecobank'), ('gcb', 'GCB Bank'), ('fidelity', 'Fidelity Bank'), ('cal_bank', 'Cal Bank'), ('stanbic', 'Stanbic Bank'), ('absa', 'Absa Bank'), ('uba', 'UBA'), ('access', 'Access Bank'), ('zenith', 'Zenith Bank'), ('republic', 'Republic Bank'), ('prudential', 'Prudential Bank'), ('fnb', 'First National Bank'), ('standard_chartered', 'Standard Chartered'), ('societe_generale', 'Societe Generale'), ('boa', 'Bank of Africa'), ('adb', 'Agricultural Dev Bank'), ('fab', 'First Atlantic Bank'), ('omnibsic', 'OmniBSIC Bank'), ('nib', 'National Investment Bank'), ('arb_apex', 'ARB Apex Bank')], default='', help_text='Select the bank (only when account type is Bank).', max_length=30),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='mobile_network',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN'), ('vodafone', 'Vodafone'), ('airteltigo', 'AirtelTigo')], default='', help_text='Select the network (only when account type is Mobile Money).', max_length=20),
        ),
    ]
